name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Install Dependencies
      run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

    - name: Run Artisan Commands
      run: php artisan storage:link
    - name: Publish Cloudinary Config
      run: php artisan vendor:publish --provider="CloudinaryLabs\CloudinaryLaravel\CloudinaryServiceProvider" --tag="cloudinary-laravel-config"

    - name: Directory Permissions
      run: chmod -R 777 storage public bootstrap/cache
    - name: Optimize
      run: php artisan optimize

    # Optional: Run the Laravel Queue Worker (this will run only once during the workflow and won't continue running)
    - name: Run Queue Worker
      run: php artisan queue:work --daemon
      # Be cautious: The '--daemon' flag will make the worker run indefinitely, which might not be ideal for CI/CD.
